# This is a simple configuration to test Grailkit components and upload to PyPi
image: python:3.6

pipelines:

  default:
    - step:
        script:
            # install dependencies
          - pip install pyserial
          - pip install python-rtmidi
          - pip install twine
            # run tests
          - python -m unittest discover -s ./grailkit/tests -p 'test_*.py'
            # Upload to PyPi
          - bash ./deploy-pypi.sh
