# This is a simple configuration to test Grailkit components
image: python:3.5.1

pipelines:
  default:
    - step:
        script:
            # run tests
          - python --version
          - python -m unittest discover -s ./grailkit/tests -p 'test_*.py'
            # build
          - python setup.py build
