# This is a simple configuration to test Grailkit components
image: python:3.3

pipelines:
  default:
    - step:
        script:
          - pip install pyserial
          - pip install python-rtmidi
            # run tests
          - python -m unittest discover -s ./grailkit/tests -p 'test_*.py'
